name: Release

on:
  push:
    branches:
      - main
      - next
      - next-major
      - beta
      - alpha
      
jobs:
  release:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm
          
      - name: Install dependencies
        run: npm ci
          
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm run release
